### 5.1.1 CSVデータの読み込み

```{r}
library(tidyverse)
my_df <- read_csv("exam.csv")
# あるいは
my_df <- read.csv("exam.csv",
  stringsAsFactors = FALSE)

my_df # 後者を実行した場合
#>   name english math gender
#> 1    A      60   70      f
#> 2    B      90   80      m
#> 3    C      70   90      m
#> 4    D      90  100      f
```

```{r}
my_url <- "https://raw.githubusercontent.com/taroyabuki/fromzero/master/data/exam.csv"
my_df <- read_csv(my_url)
# あるいは
my_df <- read.csv(my_url, stringsAsFactors = FALSE)
```

```{r}
my_df2 <- read.csv(
  file = "exam.csv",
  stringsAsFactors = FALSE,
  row.names = 1)
my_df2
#>   english math gender
#> A      60   70      f
#> B      90   80      m
#> C      70   90      m
#> D      90  100      f
```

### 5.1.2 CSVファイルへの書き出し

```{r}
my_df %>% write_csv("exam2.csv")
# あるいは
my_df %>% write.csv(file = "exam2.csv",
  row.names = FALSE) # 行名を出力しない．
```

```{r}
my_df2 %>% write.csv("exam3.csv")
```

### 5.1.3 文字コード

```{r}
library(tidyverse)
my_df <- read_csv(file = "exam.csv",
  locale = locale(encoding = "UTF-8"))
# あるいは
my_df <- read.csv(file = "exam.csv",
  stringsAsFactors = FALSE,
  fileEncoding = "UTF-8")
```

```{r}
my_df %>% write_csv("exam2.csv")
# あるいは
my_df %>% write.csv(file = "exam2.csv", row.names = FALSE, fileEncoding = "UTF-8")
```

### 5.1.4 ウェブ上の表

```{r}
library(tidyverse)
my_url <- "https://github.com/taroyabuki/fromzero/blob/master/data/exam.csv"
my_tables <- xml2::read_html(my_url) %>% rvest::html_table()
```

```{r}
my_tables 
[[1]]
  X1   X2      X3   X4     X5
1 NA name english math gender
2 NA    A      60   70      f
3 NA    B      90   80      m
4 NA    C      70   90      m
5 NA    D      90  100      f
```

```{r}
tmp <- my_tables[[1]]
tmp
  X1   X2      X3   X4     X5
1 NA name english math gender
2 NA    A      60   70      f
3 NA    B      90   80      m
4 NA    C      70   90      m
5 NA    D      90  100      f
```

```{r}
# 1行目のデータを使って列の名前を付け直す．
colnames(tmp) <- tmp[1,]

# 1行目と1列目を削除する．
my_data <- tmp[-1 ,-1]
my_data
  name english math gender
2    A      60   70      f
3    B      90   80      m
4    C      70   90      m
5    D      90  100      f
```

