### 7.7.1 第1の例（訓練誤差が0になる例）

```{r}
library(tidyverse)
library(caret)
my_data <- cars
my_idx <- c(2, 7, 11, 18, 27, 30, 34, 38, 39, 44) # 抜き出すデータの番号
my_train <- my_data[my_idx, ]                     # データを抜き出す．
```

```{r}
my_result <- train(form = dist ~ poly(speed, degree = 10, raw = TRUE),
                   data = my_train, method = "lm")
```

```{r}
my_pred <- my_result %>% predict(my_train)
RMSE(my_pred, my_train$dist)
#> [1] 4.084382e-07
```

```{r}
f <- function(x) { my_result %>% predict(data.frame(speed = x)) }

my_data %>% ggplot(aes(x = speed, y = dist)) +
  coord_cartesian(ylim = c(0, 120)) + # y座標の描画範囲
  geom_point(data = my_train, color = "red", size = 3) + # 訓練データ
  geom_point(data = my_data[-my_idx, ]) + # 訓練に使わなかったデータ
  stat_function(fun = f)
```

```{r}
my_result$results$RMSE
#> [1] 4016.54
```

### 7.7.2 第2の例（訓練誤差が同じになるデータ）

```{r}
library(tidyverse)
library(caret)
my_data <- data.frame(
  X1 = c(10, 8, 13, 9, 11, 14, 6, 4, 12, 7, 5),
  X2 = c(8, 8, 8, 8, 8, 8, 8, 19, 8, 8, 8),
  Y1 = c(8.04, 6.95, 7.58, 8.81, 8.33, 9.96, 7.24, 4.26, 10.84, 4.82, 5.68),
  Y2 = c(9.14, 8.14, 8.74, 8.77, 9.26, 8.10, 6.13, 3.10, 9.13, 7.26, 4.74),
  Y3 = c(7.46, 6.77, 12.74, 7.11, 7.81, 8.84, 6.08, 5.39, 8.15, 6.42, 5.73),
  Y4 = c(6.58, 5.76, 7.71, 8.84, 8.47, 7.04, 5.25, 12.50, 5.56, 7.91, 6.89))

my_f <- function(x) {
  my_result <- train(form = x, data = my_data, method = "lm")
  my_result$results$RMSE
}

my_v <- c(Y1 ~ X1, Y2 ~ X1, Y3 ~ X1, Y4 ~ X2)
my_v %>% map_dbl(my_f)
#> [1] 1.447843 1.534242 1.312634 2.112059
```

