### 4.1.1 平均・分散・標準偏差

```{r}
x <- c(165, 170, 175, 180, 185)
mean(x) # 平均
#> [1] 175
```

### 4.1.1 平均・分散・標準偏差

```{r}
n <- length(x) # サンプルサイズ
sum(x) / n
#> [1] 175
```

### 4.1.1 平均・分散・標準偏差

```{r}
y <- c(173, 174, 175, 176, 177)
mean(y)
#> [1] 175
```

### 4.1.1 平均・分散・標準偏差

```{r}
var(x) # xの分散
#> [1] 62.5

var(y) # yの分散
#> [1] 2.5
```

### 4.1.1 平均・分散・標準偏差

```{r}
sum((x - mean(x))^2) / (n - 1) # 分散
#> [1] 62.5
```

### 4.1.1 平均・分散・標準偏差

```{r}
sd(x) # xの標準偏差
#> [1] 7.905694

sd(y) # yの標準偏差
#> [1] 1.581139
```

### 4.1.1 平均・分散・標準偏差

```{r}
var(x)**0.5 # xの標準偏差
#> [1] 7.905694
```

### 4.1.1 平均・分散・標準偏差

```{r}
psych::describe(x)
#>    vars n mean   sd ...
#> X1    1 5  175 7.91 ...

# あるいは

pastecs::stat.desc(x)
#>      nbr.val ...   std.dev ...
#>    5.0000000 ... 7.9056942 ...
```

### 4.1.1 平均・分散・標準偏差

```{r}
quantile(x)
#>   0%  25%  50%  75% 100% 
#>  165  170  175  180  185 
```

#### 4.1.1.1 不偏分散とその非負の平方根

```{r}
x <- c(165, 170, 175, 180, 185)
n <- length(x)

var(x)
#> [1] 62.5

var(x) * (n - 1) / n
# あるいは
mean((x - mean(x))^2)
#> [1] 50
```

#### 4.1.1.1 不偏分散とその非負の平方根

```{r}
# √不偏分散
sd(x)
#> [1] 7.905694

# √標本分散
sd(x) * sqrt((n - 1) / n)
# あるいは
mean((x - mean(x))^2)^0.5
#> [1] 7.071068
```

#### 4.1.1.1 不偏分散とその非負の平方根

```{r}
sd(x) / length(x)**0.5
#> [1] 3.535534
```

### 4.1.2 データフレームの統計処理

```{r}
library(tidyverse)

my_df <- data.frame(
  name    = c("A", "B", "C", "D"),
  english = c( 60,  90,  70,  90),
  math    = c( 70,  80,  90, 100),
  gender  = c("f", "m", "m", "f"))
```

#### 4.1.2.1 列ごとの集計

```{r}
var(my_df$english)
#> [1] 225
```

#### 4.1.2.1 列ごとの集計

```{r}
# 結果はベクタ
my_df[, c(2, 3)] %>% sapply(var)
#> english     math 
#> 225.0000 166.6667

# 結果はリスト
my_df[, c(2, 3)] %>% lapply(var)
#> $english
#> [1] 225
#> 
#> $math
#> [1] 166.6667

# 結果はデータフレーム
my_df[, c(2, 3)] %>% # 2, 3列目
  summarize(across(  # の
    everything(),    # 全ての
    var))            # 不偏分散
# あるいは
my_df %>%              # データフレーム
  summarize(across(    # の
    where(is.numeric), # 数値の列の
    var))              # 不偏分散
# あるいは
my_df %>%              # データフレーム
  summarize(across(    # の
    where(is.numeric), # 数値の列の
    function(x) { var(x) })) # 不偏分散

#>   english     math
#> 1     225 166.6667
```

#### 4.1.2.1 列ごとの集計

```{r}
psych::describe(my_df)
#>         vars n mean    sd ...
#> name*      1 4  2.5  1.29 ...
#> english    2 4 77.5 15.00 ...
#> math       3 4 85.0 12.91 ...
#> gender*    4 4  1.5  0.58 ...

# あるいは

pastecs::stat.desc(my_df)
#>               english        math
#> nbr.val     4.0000000   4.0000000
#> nbr.null    0.0000000   0.0000000
#> nbr.na      0.0000000   0.0000000
#> （以下略）
```

#### 4.1.2.2 分割表とグループごとの集計

```{r}
table(my_df$gender)

#> f m 
#> 2 2 
```

#### 4.1.2.2 分割表とグループごとの集計

```{r}
my_df2 <- data.frame(
  gender = my_df$gender,
  excel = my_df$math >= 80)
table(my_df2)

#>       excel
#> gender FALSE TRUE
#>      f     1    1
#>      m     0    2
```

#### 4.1.2.2 分割表とグループごとの集計

```{r}
my_df %>% group_by(gender) %>%
  summarize(across(
    where(is.numeric), mean),
    .groups = "drop") # グループ化解除

#> # A tibble: 2 x 3
#>   gender english  math
#>   <chr>    <dbl> <dbl>
#> 1 f           75    85
#> 2 m           80    85
```

